📎 Drag'n'drop support
nastoletni/code pull request #4
Opened 2017-06-18 13:32 UTC by bartekjacak

When @Albert221 will style dragEnter behaviour I think it will be finished.

2017-06-18 17:21 UTC, Albert221 commented
CSS commited, sorry for `--force`. I have problem with uploading files. ~70% files I'm trying to drop throw this error:

> Uncaught TypeError: Cannot read property 'name' of undefined
>     at Object.getFileName (http://code.nastoletni.dev/app.js:134:16)
>     at Object.fillFieldset (http://code.nastoletni.dev/app.js:105:24)
>     at emptyFieldsets.forEach (http://code.nastoletni.dev/app.js:91:56)
>     at Array.forEach (native)
>     at window.addEventListener (http://code.nastoletni.dev/app.js:91:22)

And this is not a problem with permissions or anything. The above is a `package.json` from this repo. Althought for example `README.md` works just fine. Can you fix it?

2017-06-18 20:46 UTC, bartekjacak commented
Should be working now.

2017-06-18 21:48 UTC, Albert221 requested changes

2017-06-18 21:48 UTC, Albert221 commented on resources/views/home.twig
> +        <div class="drop-overlay">
I think that this could be appended via JS, because without JS it does not make any sense anyway

2017-06-18 21:48 UTC, Albert221 commented on web/app.js
> +    return file.type.indexOf('text') == 0 || file.type.indexOf('application') == 0;
There is many edge-cases that this does not cover and this also does not allow some files to be dropped. I think that we should create a whitelist of MIME types that will be allowed to be dropped. I can maintain that list, but you need to provide me the basis to work with.

2017-06-19 16:58 UTC, Albert221 requested changes
I think that these .DS_Store are not supposed to be there.

2017-06-19 19:24 UTC, bartekjacak commented
Oh, I will get rid of those .DS_Store files, sorry for them.

Soon I'll write a method to append overlay element and a class for appending new fieldsets. In my last commit I've included whitelist, which was made really quickly, so check it, remove unnecessary positions and add necessary ones.

Also I've left a console log, which returns MIME type of uploading file and it's presence in a whitelist. Thanks to it you can easily fill whitelist with missing positions and when the whitelist will be completed it can be deleted.

2017-06-20 06:02 UTC, Albert221 approved these changes

2017-06-20 06:03 UTC, Albert221 commented on .gitignore
> +*/.DS_STORE
can you delete this line? `.DS_STORE` already means a file that is *anywhere*

2017-06-20 06:08 UTC, Albert221 commented on web/app.js
> +    window.addEventListener("dragenter", (event) => {
CS: here you are using quotation marks but below apostrophes. Stay with apostrophes.

2017-06-23 14:34 UTC, Albert221 commented
I removed ErrorPopup because I don't think it will be needed. In that case I am not deleting this branch, so everything will be kept in GitHub.

I've also Googled about MIME types and the think that I am sure of is that creating (and maintaining!) the list of acceptable MIME types is a very *very* bad idea, because the number of these types is huge and it will be a big problem for UX if one will want to drop an ordinary file that is not taken into account of those types.

As of that, everything is working, validation is (IMO) good enough. Merging.

2017-06-23 14:37 UTC, merged